FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt test.json preprocessing.py main.py ./

RUN pip install --no-cache-dir -r requirements.txt

RUN python -m spacy download en_core_web_lg

EXPOSE 8000

CMD ["python", "main.py"]